import path from 'node:path';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    host: '0.0.0.0',
    port: 5173,
    allowedHosts: ['bopacorp-crm.jointrymyride.com'],
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    exclude: [
      '**/node_modules/**',
      '.opencode/**',
      'dist/**',
      'coverage/**',
      'e2e/**',
      'src/integration/**',
    ],
    testTimeout: 15000,
    env: {
      VITE_API_URL: 'http://test.local/api/v1',
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'html'],
      reportsDirectory: './coverage',
      include: [
        'src/modules/clients/clients.service.ts',
        'src/modules/clients/components/BusinessClientForm.tsx',
        'src/modules/clients/hooks/useBusinessClients.ts',
        'src/modules/catalog/catalog.service.ts',
        'src/modules/catalog/components/CatalogItemForm.tsx',
        'src/modules/catalog/hooks/useCatalogItems.ts',
        'src/modules/catalog/hooks/useCategories.ts',
        'src/modules/catalog/hooks/useContactRequests.ts',
        'src/modules/auth/components/Can.tsx',
        'src/modules/auth/components/RequireAuth.tsx',
        'src/modules/auth/components/RequirePermission.tsx',
        'src/modules/auth/context/AuthContext.tsx',
        'src/modules/auth/hooks/usePermission.ts',
        'src/modules/auth/pages/LoginPage.tsx',
        'src/modules/negotiations/negotiations.service.ts',
        'src/modules/negotiations/components/ChangeStateDialog.tsx',
        'src/modules/negotiations/components/CreateNegotiationDialog.tsx',
        'src/modules/negotiations/components/CreateVisitSheet.tsx',
        'src/modules/negotiations/components/NegotiationForm.tsx',
        'src/modules/negotiations/components/VisitActions.tsx',
        'src/modules/negotiations/components/MatricesTab.tsx',
        'src/modules/negotiations/hooks/useNegotiations.ts',
        'src/modules/negotiations/hooks/useVisits.ts',
        'src/modules/matrices/matrices.service.ts',
        'src/modules/matrices/hooks/useMatrices.ts',
        'src/modules/matrices/hooks/useMatrix.ts',
        'src/modules/matrices/hooks/useMatrixAttachments.ts',
        'src/modules/documentation/documentation.service.ts',
        'src/modules/documentation/components/DocumentActions.tsx',
        'src/modules/documentation/components/DocumentTypeSheet.tsx',
        'src/modules/documentation/components/DocumentUploadDialog.tsx',
        'src/modules/documentation/components/RejectDocumentDialog.tsx',
        'src/modules/documentation/hooks/useDocuments.ts',
        'src/modules/documentation/hooks/useDocumentTypes.ts',
        'src/modules/reports/reports.service.ts',
        'src/modules/reports/components/ExportButton.tsx',
        'src/modules/reports/components/PerformanceChart.tsx',
        'src/modules/reports/hooks/useAdvisorMetrics.ts',
        'src/modules/reports/hooks/useAdvisorPerformance.ts',
        'src/modules/reports/hooks/useRecentActivity.ts',
        'src/modules/reports/hooks/useReportExports.ts',
        'src/modules/reports/hooks/useSalesTargets.ts',
        'src/modules/reports/hooks/useTeamAdvisors.ts',
        'src/modules/reports/pages/ReportsPage.tsx',
        'src/modules/org/org.service.ts',
        'src/modules/org/users.service.ts',
        'src/modules/org/components/CreateEmployeeSheet.tsx',
        'src/modules/org/components/UnlockAccountDialog.tsx',
        'src/modules/org/hooks/useAdvisors.ts',
        'src/modules/org/hooks/useDepartments.ts',
        'src/modules/org/hooks/useOrgRoles.ts',
        'src/modules/org/hooks/useRoles.ts',
        'src/modules/employability/employability.service.ts',
        'src/modules/employability/lib/state.ts',
        'src/modules/employability/components/VacancyForm.tsx',
        'src/modules/employability/components/ApplicationActions.tsx',
        'src/modules/employability/components/RejectApplicationDialog.tsx',
        'src/modules/employability/hooks/useVacancies.ts',
        'src/modules/employability/hooks/useJobApplications.ts',
        'src/modules/overview/utils.ts',
        'src/services/api.ts',
        'src/services/auth-storage.ts',
        'src/services/auth.service.ts',
        'src/services/jwt.ts',
      ],
      exclude: [
        'src/test/**',
        '**/*.test.*',
        '**/*.spec.*',
        'src/components/ui/**',
        'src/assets/**',
        'src/**/*.d.ts',
      ],
      thresholds: {
        lines: 80,
      },
    },
  },
});
